version: 2.1

executors:
  node-docker-executor:
    docker:
      - image: circleci/node:18
      - image: docker:24.0.2 # Docker daemon
    working_directory: ~/project

jobs:
  build-and-push:
    executor: node-docker-executor
    steps:
      - checkout # Step 1: Checkout code

      # Step 2: Set up SSH for private repo access
      - add_ssh_keys:
          fingerprints:
            - SHA256:1i68JR5gp0mkAS20d+WB0T8IhDLKg9T1TsnvvwtytcM # Replace with your SSH key fingerprint

      # Step 3: Install dependencies
      - run:
          name: Install dependencies
          command: npm ci

      # Step 4: Build the application
      - run:
          name: Build the application
          command: npm run build

      # Step 5: Extract version from package.json
      - run:
          name: Extract version
          command: |
            VERSION=$(jq -r .version package.json)
            echo "export VERSION=$VERSION" >> $BASH_ENV
      - run:
          name: Print version
          command: echo "Version is $VERSION"

      # Step 6: Log in to Docker Hub
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin

      # Step 7: Build and push Docker images
      - run:
          name: Build and push Docker image
          command: |
            export VERSION=$VERSION
            echo "Building and tagging Docker images..."
            DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME VERSION=$VERSION docker compose -f docker-compose.yml build --no-cache --build-arg VERSION=$VERSION

            docker tag $DOCKERHUB_USERNAME/test-circleci:$VERSION-backend $DOCKERHUB_USERNAME/test-circleci:latest-backend
            docker push $DOCKERHUB_USERNAME/test-circleci:$VERSION-backend
            docker push $DOCKERHUB_USERNAME/test-circleci:latest-backend

      # Step 8: Clean up
      - run:
          name: Clean up Docker images
          command: docker system prune -af --volumes

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push
