version: 2.1

executors:
  node-docker-executor:
    docker:
      - image: cimg/node:18.0 # Node.js image
    working_directory: ~/project

jobs:
  build-and-push:
    executor: node-docker-executor
    steps:
      # Step 1: Check out the code
      - checkout

      # Step 2: Set up SSH for accessing private repositories
      - add_ssh_keys:
          fingerprints:
            - SHA256:1i68JR5gp0mkAS20d+WB0T8IhDLKg9T1TsnvvwtytcM # Replace with your actual SSH key fingerprint

      # Step 3: Set up the remote Docker environment
      - setup_remote_docker

      # Step 4: Install dependencies
      - run:
          name: Install dependencies
          command: npm ci

      # Step 5: Build the application
      - run:
          name: Build the application
          command: npm run build

      # Step 6: Extract the version from package.json
      - run:
          name: Extract version
          command: |
            VERSION=$(jq -r .version package.json)
            echo "export VERSION=$VERSION" >> $BASH_ENV
      - run:
          name: Print version
          command: echo "Version is $VERSION"

      # Step 7: Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin

      # Step 8: Build and push Docker images
      - run:
          name: Build and push Docker image
          command: |
            echo "Building and tagging Docker images..."
            docker compose -f docker-compose.yml build --no-cache --build-arg VERSION=$VERSION
            docker tag $DOCKERHUB_USERNAME/test-circleci:$VERSION-backend $DOCKERHUB_USERNAME/test-circleci:latest-backend
            docker push $DOCKERHUB_USERNAME/test-circleci:$VERSION-backend
            docker push $DOCKERHUB_USERNAME/test-circleci:latest-backend

      # Step 9: Clean up Docker images
      - run:
          name: Clean up Docker images
          command: docker system prune -af --volumes

workflows:
  version: 2.1
  build-and-push-workflow:
    jobs:
      - build-and-push
